Tekton:
git-clone task:
Need to set a outdirectory, you can do it creating a new workspace and set the output to this workspace, sample:

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
  namespace: camel-quarkus-openapi
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/rafamqrs/camel-quarkus-openapi.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
        - name: subdirectory
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
  workspaces:
    - name: source



If the registry required an authentication, you must to create a secret:
oc create secret docker-registry registrycreds \
--docker-server registry.example.com \
--docker-username youruser \
--docker-password yourpassword
<---->
OR
<---->
oc create secret generic registrycreds --from-file .dockerconfigjson=${XDG_RUNTIME_DIR}/containers/auth.json --type kubernetes.io/dockerconfigjson

oc secrets link default registrycred --for pull
oc secrets link builder registrycreds



